### ISSUE TITLE
Can't get it to compile

### ISSUE THREAD

**Issue by chilternflyer** [f2knpw/RC-plane-Sound-Machine#2]
I just cannot get this to compile. :-(
Ardunio IDE 2.3.6 - all of my libraries are up to date.
I've got a NodeMCU (12F chip) that I've used in another project. It compiles and loads OK. So the IDE is working.
I think that RMTMEM is in the ESP library? So how old does the library have to be?

Any help appreciated. I'd love to be able to get this working.

This is what I get:-
In file included from D:\Documents\Arduino\RCSound\ESP32_sound_generator\esp32-rmt-pwm-reader.h:18,
                 from D:\Documents\Arduino\RCSound\ESP32_sound_generator\esp32-rmt-pwm-reader.cpp:10:
C:\Users\Mitch\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.4-2f7dcd86-v1\esp32/include/driver/deprecated/driver/rmt.h:18:2: warning: #warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h" [-Wcpp]
   18 | #warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h"
      |  ^~~~~~~
D:\Documents\Arduino\RCSound\ESP32_sound_generator\esp32-rmt-pwm-reader.cpp: In function 'void rmt_isr_handler(void*)':
D:\Documents\Arduino\RCSound\ESP32_sound_generator\esp32-rmt-pwm-reader.cpp:68:39: error: 'RMTMEM' was not declared in this scope
   **_68 |         volatile rmt_item32_t *item = RMTMEM.chan[channel].data32;_**
      |                                       ^~~~~~
In file included from D:\Documents\Arduino\RCSound\ESP32_sound_generator/esp32-rmt-pwm-reader.h:18,
                 from D:\Documents\Arduino\RCSound\ESP32_sound_generator\ESP32_sound_generator.ino:2:
C:\Users\Mitch\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.4-2f7dcd86-v1\esp32/include/driver/deprecated/driver/rmt.h:18:2: warning: #warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h" [-Wcpp]
   18 | #warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h"
      |  ^~~~~~~
D:\Documents\Arduino\RCSound\ESP32_sound_generator\ESP32_sound_generator.ino: In function 'bool ReceiveMp3Command()':
D:\Documents\Arduino\RCSound\ESP32_sound_generator\ESP32_sound_generator.ino:219:1: error: no return statement in function returning non-void [-Werror=return-type]
  219 | }
      | ^
cc1plus.exe: some warnings being treated as errors
exit status 1

Compilation error: 'RMTMEM' was not declared in this scope

**Comment by f2knpw** [comment]
please read carefully the hackaday's project page. The RMT lib only works with 1.0.6 for the Espressif package

"IMPORTANT : this library only works with version 1.0.6 of ESP32 Espressif board...."

**Comment by chilternflyer** [comment]
Yes Sorry. I did read that but didn't understand how to fix it. I've fixed the Espressif library now (Tools>library manager>Boards>ESP32 Espressif) and have got it to compile now! Thanks for your help.
